version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: src/Backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
